import type { LanguageCode, NutritionRow } from "./types.js";

export type NutrientCatalogItem = Pick<NutritionRow, "id" | "label" | "indent">;

export const NUTRIENT_CATALOG: NutrientCatalogItem[] = [
  nutrient("energy", {
    EN: "energy",
    HR: "energija",
    CS: "energetická hodnota",
    DA: "energi",
    NL: "energie",
    ET: "energiasisaldus",
    FI: "energia",
    FR: "énergie",
    DE: "Energie",
    EL: "ενέργεια",
    HU: "energia",
    IT: "energia",
    PL: "wartość energetyczna (energia)",
    PT: "energia",
    RO: "valoare energetică",
    SK: "Energia",
    SL: "energijska vrednost",
    ES: "valor energético",
    SV: "Energi",
    NO: "energi"
  }),
  nutrient("fat", {
    EN: "fat",
    HR: "masti",
    CS: "tuky",
    DA: "fedt",
    NL: "vetten",
    ET: "rasvad",
    FI: "rasva",
    FR: "matières grasses",
    DE: "Fett",
    EL: "λιπαρά",
    HU: "zsír",
    IT: "grassi",
    PL: "tłuszcz",
    PT: "lípidos",
    RO: "grăsimi",
    SK: "tuky",
    SL: "maščobe",
    ES: "grasas",
    SV: "Fett",
    NO: "fett"
  }),
  nutrient("saturates", {
    EN: "of which saturates",
    HR: "od kojih zasićene masne kiseline",
    CS: "z toho nasycené mastné kyseliny",
    DA: "heraf mættede fedtsyrer",
    NL: "waarvan verzadigde vetzuren",
    ET: "millest küllastunud rasvhapped",
    FI: "josta tyydyttynyttä",
    FR: "dont acides gras saturés",
    DE: "davon gesättigte Fettsäuren",
    EL: "εκ των οποίων κορεσμένα",
    HU: "amelyből telített zsírsavak",
    IT: "di cui acidi grassi saturi",
    PL: "w tym kwasy tłuszczowe nasycone (kwasy nasycone)",
    PT: "dos quais saturados",
    RO: "din care acizi grași saturați",
    SK: "z toho nasýtené mastné kyseliny",
    SL: "od tega nasičene maščobe",
    ES: "de las cuales saturadas",
    SV: "varav mättat fett",
    NO: "hvorav mettede fettsyrer"
  }, true),
  nutrient("mono_unsaturates", {
    EN: "of which mono-unsaturates",
    HR: "od kojih jednostruko nezasićene masne kiseline",
    CS: "z toho mononenasycené mastné kyseliny (mononenové mastné kyseliny)",
    DA: "heraf enkeltumættede fedtsyrer",
    NL: "waarvan enkelvoudig onverzadigde vetzuren",
    ET: "millest monoküllastumata rasvhapped",
    FI: "josta kertatyydyttymättömät rasvat",
    FR: "dont acides gras mono-insaturés",
    DE: "davon einfach ungesättigte Fettsäuren",
    EL: "εκ των οποίων μονοακόρεστα",
    HU: "amelyből egyszeresen telítetlen zsírsavak",
    IT: "di cui acidi grassi monoinsaturi",
    PL: "w tym kwasy tłuszczowe jednonienasycone (jednonienasycone)",
    PT: "dos quais monoinsaturados",
    RO: "din care acizi grași mononesaturați",
    SK: "z toho mononenasýtené mastné kyseliny",
    SL: "od tega enkrat nenasičene maščobe",
    ES: "de las cuales monoinsaturadas",
    SV: "varav enkelomättat fett",
    NO: "hvorav en-umettede fettsyrer"
  }, true),
  nutrient("polyunsaturates", {
    EN: "of which polyunsaturates",
    HR: "od kojih višestruko nezasićene masne kiseline",
    CS: "z toho polynenasycené mastné kyseliny (polyenové mastné kyseliny)",
    DA: "heraf flerumættede fedtsyrer",
    NL: "waarvan meervoudig onverzadigde vetzuren",
    ET: "millest polüküllastumata rasvhapped",
    FI: "josta monityydyttymättömät rasvat",
    FR: "dont acides gras polyinsaturés",
    DE: "davon mehrfach ungesättigte Fettsäuren",
    EL: "εκ των οποίων πολυακόρεστα",
    HU: "amelyből többszörösen telítetlen zsírsavak",
    IT: "di cui acidi grassi polinsaturi",
    PL: "w tym kwasy tłuszczowe wielonienasycone (wielonienasycone)",
    PT: "dos quais polinsaturados",
    RO: "din care acizi grași polinesaturați",
    SK: "z toho polynenasýtené mastné kyseliny",
    SL: "od tega večkrat nenasičene maščobe",
    ES: "de las cuales poliinsaturadas",
    SV: "varav fleromättat fett",
    NO: "hvorav flerumettede fettsyrer"
  }, true),
  nutrient("carbohydrate", {
    EN: "carbohydrate",
    HR: "ugljikohidrati",
    CS: "sacharidy",
    DA: "kulhydrat",
    NL: "koolhydraten",
    ET: "süsivesikud",
    FI: "hiilihydraatit",
    FR: "glucides",
    DE: "Kohlenhydrate",
    EL: "υδατάνθρακες",
    HU: "szénhidrát",
    IT: "carboidrati",
    PL: "węglowodany",
    PT: "hidratos de carbono",
    RO: "glucide",
    SK: "sacharidy",
    SL: "ogljikovi hidrati",
    ES: "hidratos de carbono",
    SV: "Kolhydrat",
    NO: "karbohydrater"
  }),
  nutrient("sugars", {
    EN: "of which sugars",
    HR: "od kojih šećeri",
    CS: "z toho cukry",
    DA: "heraf sukkerarter",
    NL: "waarvan suikers",
    ET: "millest suhkrud",
    FI: "josta sokereita",
    FR: "dont sucres",
    DE: "davon Zucker",
    EL: "εκ των οποίων σάκχαρα",
    HU: "amelyből cukrok",
    IT: "di cui zuccheri",
    PL: "w tym cukry",
    PT: "dos quais açúcares",
    RO: "din care zaharuri",
    SK: "z toho cukry",
    SL: "od tega sladkorji",
    ES: "de las cuales azúcares",
    SV: "varav sockerarter",
    NO: "hvorav sukkerarter"
  }, true),
  nutrient("polyols", {
    EN: "of which polyols",
    HR: "od kojih polioli",
    CS: "z toho polyalkoholy",
    DA: "heraf polyoler",
    NL: "waarvan polyolen",
    ET: "millest polüoolid",
    FI: "josta polyolit",
    FR: "dont polyols",
    DE: "davon mehrwertige Alkohole",
    EL: "εκ των οποίων πολυόλες",
    HU: "amelyből poliolok",
    IT: "di cui polioli",
    PL: "w tym alkohole wielowodorotlenowe (poliole)",
    PT: "dos quais polióis",
    RO: "din care polioli",
    SK: "z toho alkoholické cukry (polyoly)",
    SL: "od tega polioli",
    ES: "de las cuales polialcoholes",
    SV: "varav polyoler",
    NO: "hvorav polyoler"
  }, true),
  nutrient("starch", {
    EN: "of which starch",
    HR: "od kojih škrob",
    CS: "z toho škroby",
    DA: "heraf stivelse",
    NL: "waarvan zetmeel",
    ET: "millest tärklis",
    FI: "josta tärkkelys",
    FR: "dont amidon",
    DE: "davon Stärke",
    EL: "εκ των οποίων άμυλο",
    HU: "amelyből keményítő",
    IT: "di cui amido",
    PL: "w tym skrobia",
    PT: "dos quais amido",
    RO: "din care amidon",
    SK: "z toho škrob",
    SL: "od tega škrob",
    ES: "de las cuales almidón",
    SV: "varav stärkelse",
    NO: "hvorav stivelse"
  }, true),
  nutrient("fiber", {
    EN: "fibre",
    HR: "vlakna",
    CS: "vláknina",
    DA: "kostfibre",
    NL: "vezels",
    ET: "kiudained",
    FI: "ravintokuitu",
    FR: "fibres alimentaires",
    DE: "Ballaststoffe",
    EL: "εδώδιμες ίνες",
    HU: "rost",
    IT: "fibre",
    PL: "błonnik",
    PT: "fibra",
    RO: "fibre",
    SK: "vláknina",
    SL: "prehranske vlaknine",
    ES: "fibra alimentaria",
    SV: "Fiber",
    NO: "kostfiber"
  }),
  nutrient("protein", {
    EN: "protein",
    HR: "bjelančevine",
    CS: "bílkoviny",
    DA: "protein",
    NL: "eiwitten",
    ET: "valgud",
    FI: "proteiini",
    FR: "protéines",
    DE: "Eiweiß",
    EL: "πρωτεΐνες",
    HU: "fehérje",
    IT: "proteine",
    PL: "białko",
    PT: "proteínas",
    RO: "proteine",
    SK: "bielkoviny",
    SL: "beljakovine",
    ES: "proteínas",
    SV: "Protein",
    NO: "protein"
  }),
  nutrient("salt", {
    EN: "salt",
    HR: "sol",
    CS: "sůl",
    DA: "salt",
    NL: "zout",
    ET: "sool",
    FI: "suola",
    FR: "sel",
    DE: "Salz",
    EL: "αλάτι",
    HU: "só",
    IT: "sale",
    PL: "sól",
    PT: "sal",
    RO: "sare",
    SK: "soľ",
    SL: "sol",
    ES: "sal",
    SV: "Salt",
    NO: "salt"
  }),
  nutrient("sodium", {
    EN: "sodium",
    HR: "natrij",
    CS: "sodík",
    DA: "natrium",
    NL: "natrium",
    ET: "naatrium",
    FI: "natrium",
    FR: "sodium",
    DE: "Natrium",
    EL: "νάτριο",
    HU: "nátrium",
    IT: "sodio",
    PL: "sód",
    PT: "sódio",
    RO: "sodiu",
    SK: "sodík",
    SL: "natrij",
    ES: "sodio",
    SV: "Natrium",
    NO: "natrium"
  }),
  nutrient("vitamins_and_minerals", {
    EN: "vitamins and minerals",
    HR: "vitamini i minerali",
    CS: "vitaminy a minerální látky",
    DA: "vitaminer og mineraler",
    NL: "vitaminen en mineralen",
    ET: "vitamiinid ja mineraaltoitained",
    FI: "vitamiinit ja kivennäisaineet",
    FR: "vitamines et sels minéraux",
    DE: "Vitamine und Mineralstoffe",
    EL: "βιταμίνες και ανόργανα συστατικά",
    HU: "vitaminok és ásványi anyagok",
    IT: "vitamine e sali minerali",
    PL: "witaminy i składniki mineralne",
    PT: "vitaminas e sais minerais",
    RO: "vitamine și minerale",
    SK: "vitamíny a minerálne látky",
    SL: "vitamini in minerali",
    ES: "vitaminas y minerales",
    SV: "Vitaminer och mineralämnen",
    NO: "vitaminer og mineraler"
  }),
  nutrient("vitamin_a", commonVitamin("Vitamin A", "Vitamina A", "A-vitamiini", "A-vitamin")),
  nutrient("vitamin_c", commonVitamin("Vitamin C", "Vitamina C", "C-vitamiini", "C-vitamin")),
  nutrient("vitamin_d", commonVitamin("Vitamin D", "Vitamina D", "D-vitamiini", "D-vitamin")),
  nutrient("calcium", {
    EN: "Calcium",
    HR: "Kalcij",
    CS: "Vápník",
    DA: "Calcium",
    NL: "Calcium",
    ET: "Kaltsium",
    FI: "Kalsium",
    FR: "Calcium",
    DE: "Calcium",
    EL: "Ασβέστιο",
    HU: "Kalcium",
    IT: "Calcio",
    PL: "Wapń",
    PT: "Cálcio",
    RO: "Calciu",
    SK: "Vápnik",
    SL: "Kalcij",
    ES: "Calcio",
    SV: "Kalcium",
    NO: "Kalsium"
  }),
  nutrient("iron", {
    EN: "Iron",
    HR: "Željezo",
    CS: "Železo",
    DA: "Jern",
    NL: "IJzer",
    ET: "Raud",
    FI: "Rauta",
    FR: "Fer",
    DE: "Eisen",
    EL: "Σίδηρος",
    HU: "Vas",
    IT: "Ferro",
    PL: "Żelazo",
    PT: "Ferro",
    RO: "Fier",
    SK: "Železo",
    SL: "Železo",
    ES: "Hierro",
    SV: "Järn",
    NO: "Jern"
  }),
  nutrient("potassium", {
    EN: "Potassium",
    HR: "Kalij",
    CS: "Draslík",
    DA: "Kalium",
    NL: "Kalium",
    ET: "Kaalium",
    FI: "Kalium",
    FR: "Potassium",
    DE: "Kalium",
    EL: "Κάλιο",
    HU: "Kálium",
    IT: "Potassio",
    PL: "Potas",
    PT: "Potássio",
    RO: "Potasiu",
    SK: "Draslík",
    SL: "Kalij",
    ES: "Potasio",
    SV: "Kalium",
    NO: "Kalium"
  })
];

export function getNutrientLabel(
  id: string,
  language: LanguageCode
): string | undefined {
  return NUTRIENT_CATALOG.find((item) => item.id === id)?.label[language];
}

function nutrient(
  id: string,
  label: Record<LanguageCode, string>,
  indent = false
): NutrientCatalogItem {
  return {
    id,
    label,
    indent
  };
}

function commonVitamin(
  english: string,
  romance: string,
  finnish: string,
  hungarian: string
): Record<LanguageCode, string> {
  return {
    EN: english,
    HR: english,
    CS: english,
    DA: english,
    NL: english,
    ET: finnish,
    FI: finnish,
    FR: romance.replace("Vitamina", "Vitamine"),
    DE: english,
    EL: english.replace("Vitamin", "Βιταμίνη"),
    HU: hungarian,
    IT: romance,
    PL: english.replace("Vitamin", "Witamina"),
    PT: romance,
    RO: romance,
    SK: english.replace("Vitamin", "Vitamín"),
    SL: english,
    ES: romance,
    SV: english,
    NO: english
  };
}
