import { mmToDots } from "./measurement.js";
import { measureSegmentWidthMm, wrapRichText } from "./rich-text.js";
import type { LabelSpec, LayoutElement, LayoutResult, TableElement } from "./types.js";

export function generateZpl(layout: LayoutResult): string {
  const dpi = layout.label.dpi;
  const commands: string[] = [
    "^XA",
    "^CI28",
    `^PW${mmToDots(layout.label.widthMm, dpi)}`,
    `^LL${mmToDots(layout.label.heightMm, dpi)}`,
    "^LH0,0",
    "^FX Generated by Industrial Multilingual Composition Engine"
  ];

  for (const element of layout.elements) {
    commands.push(...elementToZpl(element, dpi, layout.label));
  }

  commands.push("^XZ");
  return commands.join("\n");
}

function elementToZpl(
  element: LayoutElement,
  dpi: number,
  label: Required<LabelSpec>
): string[] {
  switch (element.kind) {
    case "text":
      return richTextToZpl({
        xMm: element.xMm,
        yMm: element.yMm,
        widthMm: element.widthMm,
        heightMm: element.heightMm,
        text: element.text,
        fontMm: element.fontMm,
        lineHeight: element.lineHeight,
        align: element.align,
        defaultBold: element.weight === "bold",
        dpi,
        label
      });
    case "line":
      if (element.direction === "horizontal") {
        return [
          `^FO${mmToDots(element.xMm, dpi)},${mmToDots(element.yMm, dpi)}^GB${mmToDots(element.widthMm, dpi)},${Math.max(1, mmToDots(element.thicknessMm, dpi))},${Math.max(1, mmToDots(element.thicknessMm, dpi))},B,0^FS`
        ];
      }

      return [
        `^FO${mmToDots(element.xMm, dpi)},${mmToDots(element.yMm, dpi)}^GB${Math.max(1, mmToDots(element.thicknessMm, dpi))},${mmToDots(element.heightMm, dpi)},${Math.max(1, mmToDots(element.thicknessMm, dpi))},B,0^FS`
      ];
    case "box":
      return [
        `^FO${mmToDots(element.xMm, dpi)},${mmToDots(element.yMm, dpi)}^GB${mmToDots(element.widthMm, dpi)},${mmToDots(element.heightMm, dpi)},${Math.max(1, mmToDots(element.thicknessMm, dpi))},B,0^FS`
      ];
    case "qr":
      return [
        `^FO${mmToDots(element.xMm, dpi)},${mmToDots(element.yMm, dpi)}^BQN,2,4^FDLA,${escapeZplField(element.data)}^FS`
      ];
    case "barcode":
      return [
        `^FO${mmToDots(element.xMm, dpi)},${mmToDots(element.yMm, dpi)}^BY2,2,${mmToDots(element.heightMm, dpi)}^BCN,${mmToDots(element.heightMm, dpi)},N,N,N^FD${escapeZplField(element.data)}^FS`
      ];
    case "table":
      return tableToZpl(element, dpi, label);
  }
}

function tableToZpl(
  table: TableElement,
  dpi: number,
  label: Required<LabelSpec>
): string[] {
  const commands: string[] = [];
  const thicknessDots = Math.max(1, mmToDots(0.18, dpi));
  const rowCount = table.cells.length;
  const rowHeights = table.rowHeightsMm ?? Array(rowCount).fill(table.rowHeightMm);
  const tableHeight = rowHeights.reduce((total, height) => total + height, 0);

  commands.push(
    `^FO${mmToDots(table.xMm, dpi)},${mmToDots(table.yMm, dpi)}^GB${mmToDots(table.widthMm, dpi)},${mmToDots(tableHeight, dpi)},${thicknessDots},B,0^FS`
  );

  let cursorY = table.yMm;
  for (let rowIndex = 1; rowIndex < rowCount; rowIndex += 1) {
    cursorY += rowHeights[rowIndex - 1] ?? table.rowHeightMm;
    commands.push(
      `^FO${mmToDots(table.xMm, dpi)},${mmToDots(cursorY, dpi)}^GB${mmToDots(table.widthMm, dpi)},${thicknessDots},${thicknessDots},B,0^FS`
    );
  }

  let cursorX = table.xMm;
  const firstRowSpansTable =
    table.cells[0]?.length === 1 &&
    (table.cells[0][0]?.colSpan ?? 1) >= table.columnFractions.length;
  const verticalStartY = firstRowSpansTable
    ? table.yMm + (rowHeights[0] ?? table.rowHeightMm)
    : table.yMm;
  const verticalHeight = tableHeight - (verticalStartY - table.yMm);

  for (let index = 0; index < table.columnFractions.length - 1; index += 1) {
    cursorX += table.widthMm * table.columnFractions[index];
    commands.push(
      `^FO${mmToDots(cursorX, dpi)},${mmToDots(verticalStartY, dpi)}^GB${thicknessDots},${mmToDots(verticalHeight, dpi)},${thicknessDots},B,0^FS`
    );
  }

  let rowY = table.yMm;
  for (let rowIndex = 0; rowIndex < table.cells.length; rowIndex += 1) {
    const row = table.cells[rowIndex];
    const rowHeight = rowHeights[rowIndex] ?? table.rowHeightMm;
    let cellX = table.xMm;
    let colIndex = 0;

    for (const cell of row) {
      const colSpan = Math.max(1, cell.colSpan ?? 1);
      const cellWidth =
        table.widthMm *
        table.columnFractions
          .slice(colIndex, colIndex + colSpan)
          .reduce((total, fraction) => total + fraction, 0);
      const fontMm = cell.fontMm ?? table.fontMm;
      const y = rowY + 0.25;
      commands.push(
        ...richTextToZpl({
          xMm: cellX + 0.55,
          yMm: y,
          widthMm: Math.max(1, cellWidth - 1.1),
          heightMm: Math.max(0.5, rowHeight - 0.35),
          text: cell.text,
          fontMm,
          lineHeight: label.visualPreset === "industrial-plain" ? 1.02 : 1.08,
          align: cell.align,
          defaultBold: cell.weight === "bold",
          dpi,
          label
        })
      );
      cellX += cellWidth;
      colIndex += colSpan;
    }

    rowY += rowHeight;
  }

  return commands;
}

function richTextToZpl({
  xMm,
  yMm,
  widthMm,
  heightMm,
  text,
  fontMm,
  lineHeight,
  align,
  defaultBold,
  dpi,
  label
}: {
  xMm: number;
  yMm: number;
  widthMm: number;
  heightMm?: number;
  text: string;
  fontMm: number;
  lineHeight: number;
  align?: "left" | "center" | "right";
  defaultBold: boolean;
  dpi: number;
  label: Required<LabelSpec>;
}): string[] {
  const commands: string[] = [];
  const maxLines =
    heightMm === undefined
      ? Number.POSITIVE_INFINITY
      : Math.max(1, Math.floor(heightMm / (fontMm * lineHeight)));
  const lines = wrapRichText(text, widthMm, fontMm).slice(0, maxLines);
  const lineAdvanceMm = fontMm * lineHeight;

  lines.forEach((line, lineIndex) => {
    let cursorX = xMm + alignmentOffsetMm(widthMm, line.widthMm, align);
    const cursorY = yMm + lineIndex * lineAdvanceMm;
    const hasMixedBold = !defaultBold && line.segments.some((segment) => segment.bold);

    if (!hasMixedBold) {
      const lineText = line.segments.map((segment) => segment.text).join("");
      if (!lineText) {
        return;
      }

      commands.push(
        `^FO${mmToDots(cursorX, dpi)},${mmToDots(cursorY, dpi)}`,
        zplFontCommand(fontMm, defaultBold, dpi, label),
        `^FD${escapeZplField(lineText)}^FS`
      );

      if (defaultBold && label.fontFamily === "zebra") {
        commands.push(
          `^FO${mmToDots(cursorX + 0.08, dpi)},${mmToDots(cursorY, dpi)}`,
          zplFontCommand(fontMm, true, dpi, label),
          `^FD${escapeZplField(lineText)}^FS`
        );
      }

      return;
    }

    for (const segment of line.segments) {
      if (!segment.text) {
        continue;
      }

      const bold = defaultBold || segment.bold;
      const segmentWidth = measureSegmentWidthMm(segment.text, fontMm, bold);
      if (/^\s+$/.test(segment.text)) {
        cursorX += segmentWidth;
        continue;
      }

      commands.push(
        `^FO${mmToDots(cursorX, dpi)},${mmToDots(cursorY, dpi)}`,
        zplFontCommand(fontMm, bold, dpi, label),
        `^FD${escapeZplField(segment.text)}^FS`
      );

      if (bold && label.fontFamily === "zebra") {
        commands.push(
          `^FO${mmToDots(cursorX + 0.08, dpi)},${mmToDots(cursorY, dpi)}`,
          zplFontCommand(fontMm, true, dpi, label),
          `^FD${escapeZplField(segment.text)}^FS`
        );
      }

      cursorX += segmentWidth;
    }
  });

  return commands;
}

function zplFontCommand(
  fontMm: number,
  bold: boolean,
  dpi: number,
  label: Required<LabelSpec>
): string {
  const height = mmToDots(fontMm, dpi);
  const widthScale =
    label.fontFamily === "zebra"
      ? bold
        ? 0.54
        : 0.5
      : label.fontFamily === "zebra-native"
        ? bold
          ? 0.62
          : 0.58
        : 0.52;
  const width = Math.max(1, mmToDots(fontMm * widthScale, dpi));

  if (label.fontFamily === "arial" || label.fontFamily === "zebra-native") {
    const fontFile = (bold ? label.zplFontBold : label.zplFontRegular).trim();
    const fallbackFontFile = label.fontFamily === "zebra-native" ? "Z:FONT8.FNT" : "E:ARIAL.TTF";
    return `^A@N,${height},${width},${fontFile || fallbackFontFile}`;
  }

  return `^A0N,${height},${width}`;
}

function alignmentOffsetMm(
  availableMm: number,
  usedMm: number,
  align: "left" | "center" | "right" | undefined
): number {
  if (align === "center") {
    return Math.max(0, (availableMm - usedMm) / 2);
  }

  if (align === "right") {
    return Math.max(0, availableMm - usedMm);
  }

  return 0;
}

function escapeZplField(value: string): string {
  return value.replace(/[\^~]/g, " ").replace(/\r?\n/g, "\\&");
}
